import comp from "D:/Project/Blog/my-blog_newtheme/src/.vuepress/.temp/pages/笔记/前端/包管理器/npm和pnpm常用命令.html.vue"
const data = JSON.parse("{\"path\":\"/%E7%AC%94%E8%AE%B0/%E5%89%8D%E7%AB%AF/%E5%8C%85%E7%AE%A1%E7%90%86%E5%99%A8/npm%E5%92%8Cpnpm%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html\",\"title\":\"npm 和 pnpm 常用命令开发文档\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"pen-to-square\",\"date\":\"2025-06-15T00:00:00.000Z\",\"order\":2,\"category\":[\"前端\"],\"tag\":[\"npm\",\"pnpm\"],\"description\":\"npm 和 pnpm 常用命令开发文档 一、概述 npm（Node Package Manager）和 pnpm（Performant npm）是 Node.js 生态系统中用于管理项目依赖、运行脚本的工具。本文档详细列出两者在不同开发场景下的常用命令，帮助开发者快速上手和切换使用。 二、项目初始化 三、依赖管理 3.1 安装依赖 3.2 卸载依赖 3...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"npm 和 pnpm 常用命令开发文档\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2025-06-15T00:00:00.000Z\\\",\\\"dateModified\\\":\\\"2025-06-19T06:28:34.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Goat_Yang\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/Yang-goat/MyBlog/%E7%AC%94%E8%AE%B0/%E5%89%8D%E7%AB%AF/%E5%8C%85%E7%AE%A1%E7%90%86%E5%99%A8/npm%E5%92%8Cpnpm%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Goat_Yang\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"npm 和 pnpm 常用命令开发文档\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"npm 和 pnpm 常用命令开发文档 一、概述 npm（Node Package Manager）和 pnpm（Performant npm）是 Node.js 生态系统中用于管理项目依赖、运行脚本的工具。本文档详细列出两者在不同开发场景下的常用命令，帮助开发者快速上手和切换使用。 二、项目初始化 三、依赖管理 3.1 安装依赖 3.2 卸载依赖 3...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2025-06-19T06:28:34.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"pnpm\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"npm\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-06-15T00:00:00.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2025-06-19T06:28:34.000Z\"}]]},\"git\":{\"createdTime\":1750000370000,\"updatedTime\":1750314514000,\"contributors\":[{\"name\":\"Yang-goat\",\"username\":\"Yang-goat\",\"email\":\"1700425119@qq.com\",\"commits\":4,\"url\":\"https://github.com/Yang-goat\"}]},\"readingTime\":{\"minutes\":5.08,\"words\":1524},\"filePathRelative\":\"笔记/前端/包管理器/npm和pnpm常用命令.md\",\"excerpt\":\"\\n<h2>一、概述</h2>\\n<p>npm（Node Package Manager）和 pnpm（Performant npm）是 Node.js 生态系统中用于管理项目依赖、运行脚本的工具。本文档详细列出两者在不同开发场景下的常用命令，帮助开发者快速上手和切换使用。</p>\\n<h2>二、项目初始化</h2>\\n\\n<h2>三、依赖管理</h2>\\n<h3>3.1 安装依赖</h3>\\n\\n<h3>3.2 卸载依赖</h3>\\n\\n<h3>3.3 更新依赖</h3>\\n\\n<h2>四、脚本执行</h2>\\n\\n<h2>五、依赖查看与清理</h2>\\n\\n<h2>六、版本控制</h2>\\n\\n<h2>七、工作空间管理（多包项目）</h2>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
