allowBuilds:
  '@parcel/watcher': false
  esbuild: true

overrides:
  cheerio@1.0.0>undici: 6.24.0
  dagre-d3-es>lodash-es: 4.18.1
  gray-matter>js-yaml: 3.14.2
  hast-util-to-html>mdast-util-to-hast: 13.2.1
  markmap-lib>markdown-it: 14.2.0
  markmap-lib>yaml: 2.9.0
  mermaid>uuid: 14.0.0
