<template><div><h1 id="font-awesome-free-图标调试" tabindex="-1"><a class="header-anchor" href="#font-awesome-free-图标调试"><span>Font Awesome Free 图标调试</span></a></h1>
<p>这里列出了 <strong>Font Awesome Free</strong> 所有常用图标，使用方法：</p>
<p>🏠 界面 / 常用</p>
<VPIcon icon="home" /> <VPIcon icon="user" /> <VPIcon icon="users" /> <VPIcon icon="cog" /> <VPIcon icon="search" /> <VPIcon icon="bell" /> <VPIcon icon="envelope" /> <VPIcon icon="comment" /> <VPIcon icon="comments" /> <VPIcon icon="book" /> <VPIcon icon="bookmark" /> <VPIcon icon="calendar" /> <VPIcon icon="clock" /> <VPIcon icon="edit" /> <VPIcon icon="trash" /> <VPIcon icon="download" /> <VPIcon icon="upload" /> <VPIcon icon="share" /> <VPIcon icon="print" /> <VPIcon icon="globe" /><p>📁 文件 / 内容</p>
<VPIcon icon="file" /> <VPIcon icon="file-alt" /> <VPIcon icon="file-code" /> <VPIcon icon="file-image" /> <VPIcon icon="file-video" /> <VPIcon icon="folder" /> <VPIcon icon="folder-open" /> <VPIcon icon="archive" /> <VPIcon icon="clipboard" /> <VPIcon icon="copy" /> <VPIcon icon="paste" /><p>⚠️ 状态 / 提示</p>
<VPIcon icon="check" /> <VPIcon icon="check-circle" /> <VPIcon icon="times" /> <VPIcon icon="times-circle" /> <VPIcon icon="exclamation" /> <VPIcon icon="exclamation-triangle" /> <VPIcon icon="info" /> <VPIcon icon="info-circle" /> <VPIcon icon="question" /> <VPIcon icon="question-circle" /> <VPIcon icon="spinner" /> <VPIcon icon="sync" /> <VPIcon icon="lock" /> <VPIcon icon="unlock" /> <VPIcon icon="shield-alt" /><p>↔️ 导航 / 动作</p>
<VPIcon icon="arrow-left" /> <VPIcon icon="arrow-right" /> <VPIcon icon="arrow-up" /> <VPIcon icon="arrow-down" /> <VPIcon icon="arrow-circle-left" /> <VPIcon icon="arrow-circle-right" /> <VPIcon icon="arrow-circle-up" /> <VPIcon icon="arrow-circle-down" /> <VPIcon icon="sign-in-alt" /> <VPIcon icon="sign-out-alt" /> <VPIcon icon="plus" /> <VPIcon icon="minus" /> <VPIcon icon="times" /> <VPIcon icon="bars" /> <VPIcon icon="ellipsis-h" /> <VPIcon icon="ellipsis-v" /><p>🎧 设备 / 媒体</p>
<VPIcon icon="camera" /> <VPIcon icon="video" /> <VPIcon icon="music" /> <VPIcon icon="play" /> <VPIcon icon="pause" /> <VPIcon icon="stop" /> <VPIcon icon="volume-up" /> <VPIcon icon="volume-down" /> <VPIcon icon="volume-mute" /> <VPIcon icon="headphones" /> <VPIcon icon="desktop" /> <VPIcon icon="laptop" /> <VPIcon icon="tablet-alt" /> <VPIcon icon="mobile-alt" /> <VPIcon icon="keyboard" /> <VPIcon icon="mouse" /> <VPIcon icon="tv" /> <VPIcon icon="wifi" /><p>💳 电商 / 金融</p>
<VPIcon icon="shopping-cart" /> <VPIcon icon="shopping-bag" /> <VPIcon icon="shopping-basket" /> <VPIcon icon="credit-card" /> <VPIcon icon="money-bill" /> <VPIcon icon="wallet" /> <VPIcon icon="gift" /> <VPIcon icon="tags" /> <VPIcon icon="tag" /> <VPIcon icon="dollar-sign" /> <VPIcon icon="yen-sign" /> <VPIcon icon="euro-sign" /> <VPIcon icon="pound-sign" /><p>🛠️ 开发 / 技术</p>
<VPIcon icon="code" /> <VPIcon icon="terminal" /> <VPIcon icon="database" /> <VPIcon icon="server" /> <VPIcon icon="bug" /> <VPIcon icon="project-diagram" /> <VPIcon icon="cloud" /> <VPIcon icon="cloud-upload-alt" /> <VPIcon icon="cloud-download-alt" /><p>🌐 品牌 (Brands)</p>
<VPIcon icon="github" /> <VPIcon icon="gitlab" /> <VPIcon icon="bitbucket" /> <VPIcon icon="npm" /> <VPIcon icon="docker" /> <VPIcon icon="js" /> <VPIcon icon="node-js" /> <VPIcon icon="vuejs" /> <VPIcon icon="react" /> <VPIcon icon="angular" /> <VPIcon icon="python" /> <VPIcon icon="java" /> <VPIcon icon="php" /> <VPIcon icon="html5" /> <VPIcon icon="css3" /> <VPIcon icon="sass" /> <VPIcon icon="less" /> <VPIcon icon="bootstrap" /> <VPIcon icon="apple" /> <VPIcon icon="android" /> <VPIcon icon="windows" /> <VPIcon icon="linux" /> <VPIcon icon="twitter" /> <VPIcon icon="facebook" /> <VPIcon icon="linkedin" /> <VPIcon icon="weixin" /> <VPIcon icon="qq" /> <VPIcon icon="weibo" /> <VPIcon icon="telegram" /> <VPIcon icon="discord" /><Comment /></div></template>


<script setup>
import Comment from "@Comment";
</script>