import comp from "D:/Project/Blog/myBlog/src/.vuepress/.temp/pages/zh/笔记/程序设计语言/python/conda.html.vue"
const data = JSON.parse("{\"path\":\"/zh/%E7%AC%94%E8%AE%B0/%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E8%AF%AD%E8%A8%80/python/conda.html\",\"title\":\"conda 指令速查表\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"pen-to-square\",\"date\":\"2025-09-27T00:00:00.000Z\",\"category\":[\"Python\"],\"tag\":[\"conda\",\"指令大全\"],\"description\":\"conda 指令速查表 Conda 是一个开源的包管理和环境管理工具，主要用于 Python 和数据科学领域。它可以帮助你快速创建独立的虚拟环境，避免依赖冲突，并支持从 conda 仓库或 pip 安装各种软件包。通过 Conda，你可以方便地切换不同项目的运行环境，管理依赖，导出与复现环境，从而让开发过程更加高效和可控。 1. Conda 基础 查看...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"conda 指令速查表\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2025-09-27T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Goat_Yang\\\",\\\"url\\\":\\\"https://mister-hope.com\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/Yang-goat/MyBlog/zh/%E7%AC%94%E8%AE%B0/%E7%A8%8B%E5%BA%8F%E8%AE%BE%E8%AE%A1%E8%AF%AD%E8%A8%80/python/conda.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Goat_Yang\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"conda 指令速查表\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"conda 指令速查表 Conda 是一个开源的包管理和环境管理工具，主要用于 Python 和数据科学领域。它可以帮助你快速创建独立的虚拟环境，避免依赖冲突，并支持从 conda 仓库或 pip 安装各种软件包。通过 Conda，你可以方便地切换不同项目的运行环境，管理依赖，导出与复现环境，从而让开发过程更加高效和可控。 1. Conda 基础 查看...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"指令大全\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"conda\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-09-27T00:00:00.000Z\"}]]},\"git\":{},\"readingTime\":{\"minutes\":1.42,\"words\":427},\"filePathRelative\":\"zh/笔记/程序设计语言/python/conda.md\",\"excerpt\":\"\\n<p>Conda 是一个开源的包管理和环境管理工具，主要用于 Python 和数据科学领域。它可以帮助你快速创建独立的虚拟环境，避免依赖冲突，并支持从 conda 仓库或 pip 安装各种软件包。通过 Conda，你可以方便地切换不同项目的运行环境，管理依赖，导出与复现环境，从而让开发过程更加高效和可控。</p>\\n<h2>1. Conda 基础</h2>\\n<p>查看 conda 版本</p>\\n<div class=\\\"language-bash line-numbers-mode\\\" data-highlighter=\\\"shiki\\\" data-ext=\\\"bash\\\" style=\\\"--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34\\\"><pre class=\\\"shiki shiki-themes one-light one-dark-pro vp-code\\\"><code class=\\\"language-bash\\\"><span class=\\\"line\\\"><span style=\\\"--shiki-light:#4078F2;--shiki-dark:#61AFEF\\\">conda</span><span style=\\\"--shiki-light:#986801;--shiki-dark:#D19A66\\\"> --version</span></span></code></pre>\\n<div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\" style=\\\"counter-reset:line-number 0\\\"><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
