import comp from "/media/goat/data/project/Blog/myBlog/src/.vuepress/.temp/pages/guides/docker/command.html.vue"
const data = JSON.parse("{\"path\":\"/guides/docker/command.html\",\"title\":\"Docker 常用指令\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"book\",\"date\":\"2025-12-14T00:00:00.000Z\",\"category\":[\"docker\"],\"tag\":[\"命令行\",\"Shell\"],\"description\":\"Docker 常用指令 说明：以下以 Docker CLI（docker 命令） 为主，按功能分块；每一块都用表格呈现，便于速查与复制。 1) 基础信息 & 帮助 查询Docker运行状态 sudo systemctl status docker --no-pager -l 重启Docker sudo systemctl restart docker ...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Docker 常用指令\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2025-12-14T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Goat_Yang\\\",\\\"url\\\":\\\"../intro.html\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/Yang-goat/MyBlog/guides/docker/command.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Goat_Yang\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Docker 常用指令\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Docker 常用指令 说明：以下以 Docker CLI（docker 命令） 为主，按功能分块；每一块都用表格呈现，便于速查与复制。 1) 基础信息 & 帮助 查询Docker运行状态 sudo systemctl status docker --no-pager -l 重启Docker sudo systemctl restart docker ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Shell\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"命令行\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-12-14T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":6.93,\"words\":2079},\"filePathRelative\":\"guides/docker/command.md\",\"excerpt\":\"\\n<blockquote>\\n<p>说明：以下以 <strong>Docker CLI（docker 命令）</strong> 为主，按功能分块；每一块都用表格呈现，便于速查与复制。</p>\\n</blockquote>\\n<hr>\\n<h2>1) 基础信息 &amp; 帮助</h2>\\n<table>\\n<thead>\\n<tr>\\n<th>目的</th>\\n<th>命令</th>\\n<th>常用参数/示例</th>\\n<th>备注</th>\\n</tr>\\n</thead>\\n<tbody>\\n<tr>\\n<td>查看版本</td>\\n<td><code>docker version</code></td>\\n<td></td>\\n<td>同时显示 Client/Server</td>\\n</tr>\\n<tr>\\n<td>查看系统信息</td>\\n<td><code>docker info</code></td>\\n<td></td>\\n<td>含存储驱动、root dir、插件等</td>\\n</tr>\\n<tr>\\n<td>帮助入口</td>\\n<td><code>docker --help</code></td>\\n<td></td>\\n<td></td>\\n</tr>\\n<tr>\\n<td>查看子命令帮助</td>\\n<td><code>docker &lt;cmd&gt; --help</code></td>\\n<td><code>docker run --help</code></td>\\n<td></td>\\n</tr>\\n<tr>\\n<td>查看 Docker 上下文</td>\\n<td><code>docker context ls</code></td>\\n<td></td>\\n<td>多 Docker 环境切换</td>\\n</tr>\\n<tr>\\n<td>切换上下文</td>\\n<td><code>docker context use &lt;name&gt;</code></td>\\n<td></td>\\n<td></td>\\n</tr>\\n<tr>\\n<td>当前登录信息</td>\\n<td><code>docker login</code> / <code>docker logout</code></td>\\n<td><code>docker login -u &lt;user&gt;</code></td>\\n<td>Registry 认证</td>\\n</tr>\\n</tbody>\\n</table>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
