import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/ai-ml/base/": "structure",
  "/ai-ml/parameter-settings/": "structure",
  "/ai-ml/machine-learning/": "structure",
  "/ai-ml/deep-learning/": "structure",
  "/ai-ml/RL/": "structure",
  "/ai-ml/other/": "structure",
  "/ai-ml/optimization/": "structure",
  "/ai-ml/problems/": "structure",
  "/ai-practice/agents/": [
    {
      text: "Agents",
      icon: "robot",
      children: "structure",
    },
    {
      text: "Obsidian + Zotero + Codex：AI 辅助科研工作流",
      icon: "robot",
      link: "/guides/paper-knowledge/ai-research-workflow.html",
    },
  ],
  "/ai-practice/prompts/": "structure",
  "/ai-practice/skills-mcp/": "structure",
  "/ai-practice/topics/": "structure",
  "/notes/language/": "structure",
  "/notes/frontend/": "structure",
  "/notes/music/": "structure",
  "/notes/hex-mahjong/": "structure",
  "/notes/Math/": "structure",
  "/notes/MCM/": "structure",
  "/notes/computer/": "structure",
  "/notes/major/": "structure",
  "/guides/git/": "structure",
  "/guides/github-projects/": "structure",
  "/guides/paper-knowledge/": "structure",
  "/guides/docker/": "structure",
  "/guides/linux/": "structure",
  "/guides/Latex/": [
    {
      text: "VSCode 中 LaTeX 环境配置",
      icon: "code",
      link: "/guides/VSCode/Latex配置.html",
    },
    {
      text: "LaTeX",
      icon: "file-lines",
      expanded: true,
      children: "structure",
    },
  ],
  "/guides/VSCode/": "structure",
  "/tests/": "structure",
  "/": [],
});
