import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/ai-ml/": [
    {
      text: "学习类算法导论",
      icon: "book",
      link: "Introduction-to-Learning-Algorithms.md",
    },
    {
      text: "深度学习",
      icon: "code",
      prefix: "deep-learning/",
      link: "deep-learning/",
      children: "structure",
    },
    {
      text: "智能优化算法",
      icon: "code",
      prefix: "optimization/",
      link: "optimization/",
      children: [
        {
          text: "优化理论",
          icon: "book",
          link: "OptimizationTheory.md",
        },
        {
          text: "智能优化算法的分类",
          icon: "layer-group",
          link: "Category.md",
        },
        {
          text: "进化算法（EA）",
          icon: "code",
          prefix: "EA/",
          link: "EA/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "多目标优化问题（MOO）",
          icon: "code",
          prefix: "MOO/",
          link: "MOO/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        // {
        //   text: "多目标进化算法（MOEA）",
        //   icon: "code",
        //   prefix: "MOEA/",
        //   link: "MOEA/",
        //   collapsible: true,
        //   expanded: false,
        //   children: "structure",
        // },
      ],
    },
    {
      text: "具体问题/案例",
      icon: "bars",
      prefix: "problems/",
      link: "problems/",
      children: "structure",
    },
  ],
  "/dev/": [
    {
      text: "程序设计语言",
      icon: "code",
      prefix: "language/",
      link: "language/",
      children: [
        {
          text: "Java",
          icon: "code",
          prefix: "java/",
          link: "java/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "python",
          icon: "code",
          prefix: "python/",
          link: "python/",
          collapsible: true,
          expanded: false,
          children: "structure",
        }
      ],
    },
    {
      text: "前端",
      icon: "laptop-code",
      prefix: "frontend/",
      link: "frontend/",
      children: "structure",
    },
  ],
  "/notes/": [
    {
      text: "专业课专题",
      icon: "graduation-cap",
      prefix: "major/",
      link: "major/",
      collapsible: true,
      expanded: false,
      children: "structure",
    },
    {
      text: "数学建模专题",
      icon: "graduation-cap",
      prefix: "MCM/",
      link: "MCM/",
      collapsible: true,
      expanded: true,
      children: "structure",
    },
    {
      text: "ACM算法专题",
      icon: "code",
      prefix: "ACMer/",
      link: "ACMer/",
      children: [
        {
          text: "竞赛板子",
          link: "竞赛板子.md",
          icon: "lightbulb",
        },
        {
          text: "基础算法",
          prefix: "基础算法/",
          link: "基础算法/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "数据结构",
          prefix: "数据结构/",
          link: "数据结构/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "图论",
          prefix: "图论/",
          link: "图论/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "动态规划(DP)",
          prefix: "动态规划(DP)/",
          link: "动态规划(DP)/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "数学与数论",
          prefix: "数学与数论/",
          link: "数学与数论/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "字符串算法",
          prefix: "字符串算法/",
          link: "字符串算法/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "计算几何",
          prefix: "计算几何/",
          link: "计算几何/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "杂项",
          prefix: "杂项/",
          link: "杂项/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
      ]
    },
  ],
  "/guides/": [
    {
      text: "Latex",
      icon: "laptop-code",
      prefix: "Latex/",
      link: "Latex/",
      children: "structure",
    },
    {
      text: "VSCode",
      icon: "laptop-code",
      prefix: "VSCode/",
      link: "VSCode/",
      children: "structure",
    },
    {
      text: "版本控制",
      icon: "laptop-code",
      prefix: "git/",
      link: "git/",
      children: "structure",
    },
    { 
      text: "Zotero",
      icon: "book",
      link: "Zotero.md",
    },
  ],
  "/tests/": "structure",
  // "/links/": "structure",
});
