import { sidebar } from "vuepress-theme-hope";

export default sidebar({
  "/ai-ml/": [
    {
      text: "通识基础",
      icon: "book",
      prefix: "base/",
      link: "base/",
      children: "structure",
    },
    {
      text: "学习类算法导论",
      icon: "book",
      link: "Introduction-to-Learning-Algorithms.md",
    },
    {
      text: "参数设置分析方法",
      icon: "code",
      prefix: "parameter-settings/",
      link: "parameter-settings/",
      children: "structure",
      collapsible: true,
      expanded: false,
    },
    {
      text: "机器学习",
      icon: "code",
      prefix: "machine-learning/",
      link: "machine-learning/",
      children: "structure",
    },
    {
      text: "深度学习",
      icon: "code",
      prefix: "deep-learning/",
      link: "deep-learning/",
      children: "structure",
    },
    {
      text: "智能优化算法",
      icon: "code",
      prefix: "optimization/",
      link: "optimization/",
      children: [
        {
          text: "优化基础理论知识",
          icon: "user-graduate",
          prefix: "Theory/",
          link: "Theory/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "进化算法（EA）",
          icon: "e",
          prefix: "EA/",
          link: "EA/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "分布估计算法（EDAs）",
          icon: "e",
          link: "EDAs.md",
        },
        {
          text: "可变邻域搜索（VNS）",
          icon: "v",
          link: "VNS.md",
        },
        {
          text: "多目标优化问题（MOO）",
          icon: "m",
          prefix: "MOO/",
          link: "MOO/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        // {
        //   text: "多目标进化算法（MOEA）",
        //   icon: "code",
        //   prefix: "MOEA/",
        //   link: "MOEA/",
        //   collapsible: true,
        //   expanded: false,
        //   children: "structure",
        // },
      ],
    },
    {
      text: "具体问题/案例",
      icon: "bars",
      prefix: "problems/",
      link: "problems/",
      children: "structure",
    },
  ],
  "/dev/": [
    {
      text: "程序设计语言",
      icon: "code",
      prefix: "language/",
      link: "language/",
      children: [
        {
          text: "Java",
          icon: "code",
          prefix: "java/",
          link: "java/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
        {
          text: "python",
          icon: "code",
          prefix: "python/",
          link: "python/",
          collapsible: true,
          expanded: false,
          children: "structure",
        }
      ],
    },
    {
      text: "前端",
      icon: "laptop-code",
      prefix: "frontend/",
      link: "frontend/",
      children: "structure",
    },
  ],
  "/notes/": [
    {
      text: "数学随记",
      icon: "m",
      prefix: "Math/",
      link: "Math/",
      collapsible: true,
      expanded: false,
      children: "structure",
    },
    {
      text: "专业课专题",
      icon: "graduation-cap",
      prefix: "major/",
      link: "major/",
      collapsible: true,
      expanded: false,
      children: "structure",
    },
    {
      text: "数学建模专题",
      icon: "graduation-cap",
      prefix: "MCM/",
      link: "MCM/",
      collapsible: true,
      expanded: true,
      children: "structure",
    },
    {
      text: "ACM算法专题",
      icon: "code",
      prefix: "ACMer/",
      link: "ACMer/",
      children: [
        {
          text: "竞赛板子",
          link: "竞赛板子.md",
          icon: "lightbulb",
        },
        {
          text: "基础算法",
          prefix: "基础算法/",
          link: "基础算法/",
          collapsible: true,
          expanded: false,
          children: "structure",
        },
      ]
    },
  ],
  "/guides/": [
    {
      text: "Linux",
      icon: "l",
      prefix: "linux/",
      link: "linux/",
      children: "structure",
    },
    {
      text: "Docker",
      icon: "d",
      prefix: "docker/",
      link: "docker/",
      children: "structure",
    },
    {
      text: "Latex",
      icon: "laptop-code",
      prefix: "Latex/",
      link: "Latex/",
      children: "structure",
    },
    {
      text: "VSCode",
      icon: "laptop-code",
      prefix: "VSCode/",
      link: "VSCode/",
      children: "structure",
    },
    {
      text: "版本控制",
      icon: "laptop-code",
      prefix: "git/",
      link: "git/",
      children: "structure",
    },
    { 
      text: "Zotero",
      icon: "book",
      link: "Zotero.md",
    },
  ],
  "/tests/": "structure",
  // "/links/": "structure",
});
