import comp from "/media/goat/data/project/Blog/myBlog/src/.vuepress/.temp/pages/ai-ml/RL/09策略梯度方法.html.vue"
const data = JSON.parse("{\"path\":\"/ai-ml/RL/09%E7%AD%96%E7%95%A5%E6%A2%AF%E5%BA%A6%E6%96%B9%E6%B3%95.html\",\"title\":\"策略梯度算法\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"8\",\"date\":\"2026-01-19T00:00:00.000Z\",\"order\":9,\"title\":\"策略梯度算法\",\"category\":[\"强化学习\"],\"description\":\"策略梯度算法（Policy Gradient Methods） 在本文中，我们将从 基于价值的方法转向基于策略的方法 基于价值函数的方法转向策略函数方法（或称为策略梯度方法） 策略表示：从表格到函数 以前，策略是通过表格表示的： 所有状态的动作概率存储在表格π(a∣s)中。表格中的每个条目由状态和动作索引。 现在，策略可以通过参数化函数表示： π(a∣...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"策略梯度算法\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2026-01-19T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Goat_Yang\\\",\\\"url\\\":\\\"../intro.html\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/Yang-goat/MyBlog/ai-ml/RL/09%E7%AD%96%E7%95%A5%E6%A2%AF%E5%BA%A6%E6%96%B9%E6%B3%95.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Goat_Yang\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"策略梯度算法\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"策略梯度算法（Policy Gradient Methods） 在本文中，我们将从 基于价值的方法转向基于策略的方法 基于价值函数的方法转向策略函数方法（或称为策略梯度方法） 策略表示：从表格到函数 以前，策略是通过表格表示的： 所有状态的动作概率存储在表格π(a∣s)中。表格中的每个条目由状态和动作索引。 现在，策略可以通过参数化函数表示： π(a∣...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2026-01-19T00:00:00.000Z\"}]]},\"git\":{},\"readingTime\":{\"minutes\":11.07,\"words\":3321},\"filePathRelative\":\"ai-ml/RL/09策略梯度方法.md\",\"excerpt\":\"\\n<p>在本文中，我们将从</p>\\n<ul>\\n<li>基于价值的方法转向基于策略的方法</li>\\n<li>基于价值函数的方法转向策略函数方法（或称为策略梯度方法）</li>\\n</ul>\\n<h2>策略表示：从表格到函数</h2>\\n<p>以前，策略是通过表格表示的：</p>\\n<ul>\\n<li>所有状态的动作概率存储在表格<span v-pre=\\\"\\\" class=\\\"katex\\\"><span class=\\\"katex-mathml\\\"><math xmlns=\\\"http://www.w3.org/1998/Math/MathML\\\"><semantics><mrow><mi>π</mi><mo stretchy=\\\"false\\\">(</mo><mi>a</mi><mi mathvariant=\\\"normal\\\">∣</mi><mi>s</mi><mo stretchy=\\\"false\\\">)</mo></mrow><annotation encoding=\\\"application/x-tex\\\">\\\\pi(a|s)</annotation></semantics></math></span><span class=\\\"katex-html\\\" aria-hidden=\\\"true\\\"><span class=\\\"base\\\"><span class=\\\"strut\\\" style=\\\"height:1em;vertical-align:-0.25em;\\\"></span><span class=\\\"mord mathnormal\\\" style=\\\"margin-right:0.03588em;\\\">π</span><span class=\\\"mopen\\\">(</span><span class=\\\"mord mathnormal\\\">a</span><span class=\\\"mord\\\">∣</span><span class=\\\"mord mathnormal\\\">s</span><span class=\\\"mclose\\\">)</span></span></span></span>中。表格中的每个条目由状态和动作索引。</li>\\n</ul>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
