import comp from "D:/Project/Blog/myBlog/src/.vuepress/.temp/pages/notes/ACMer/基础算法/二分与三分.html.vue"
const data = JSON.parse("{\"path\":\"/notes/ACMer/%E5%9F%BA%E7%A1%80%E7%AE%97%E6%B3%95/%E4%BA%8C%E5%88%86%E4%B8%8E%E4%B8%89%E5%88%86.html\",\"title\":\"二分与三分\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"code\",\"date\":\"2025-09-13T00:00:00.000Z\",\"order\":2,\"category\":[\"算法\"],\"tag\":[\"二分\",\"三分\"],\"description\":\"二分与三分 二分查找、由二分法衍生的三分法以及二分答案 二分查找 在一个有序数组中查找某一元素的算法。O(logn) 手写 STL 的二分查找 查找首个不小于给定值的元素的函数 std::lower_bound 查找首个大于给定值的元素的函数 std::upper_bound 返回值为指针，减数组首地址得到下标。 最大值最小化 要求满足某种条件的最大值...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"二分与三分\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2025-09-13T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Goat_Yang\\\",\\\"url\\\":\\\"../intro.html\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/Yang-goat/MyBlog/notes/ACMer/%E5%9F%BA%E7%A1%80%E7%AE%97%E6%B3%95/%E4%BA%8C%E5%88%86%E4%B8%8E%E4%B8%89%E5%88%86.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Goat_Yang\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"二分与三分\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"二分与三分 二分查找、由二分法衍生的三分法以及二分答案 二分查找 在一个有序数组中查找某一元素的算法。O(logn) 手写 STL 的二分查找 查找首个不小于给定值的元素的函数 std::lower_bound 查找首个大于给定值的元素的函数 std::upper_bound 返回值为指针，减数组首地址得到下标。 最大值最小化 要求满足某种条件的最大值...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"三分\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"二分\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-09-13T00:00:00.000Z\"}]]},\"git\":{},\"readingTime\":{\"minutes\":2.39,\"words\":718},\"filePathRelative\":\"notes/ACMer/基础算法/二分与三分.md\",\"excerpt\":\"\\n<p>二分查找、由二分法衍生的三分法以及二分答案</p>\\n<h2>二分查找</h2>\\n<p>在一个有序数组中查找某一元素的算法。<span v-pre=\\\"\\\" class=\\\"katex\\\"><span class=\\\"katex-mathml\\\"><math xmlns=\\\"http://www.w3.org/1998/Math/MathML\\\"><semantics><mrow><mi>O</mi><mo stretchy=\\\"false\\\">(</mo><mi>log</mi><mo>⁡</mo><mi>n</mi><mo stretchy=\\\"false\\\">)</mo></mrow><annotation encoding=\\\"application/x-tex\\\">O(\\\\log n)</annotation></semantics></math></span><span class=\\\"katex-html\\\" aria-hidden=\\\"true\\\"><span class=\\\"base\\\"><span class=\\\"strut\\\" style=\\\"height:1em;vertical-align:-0.25em;\\\"></span><span class=\\\"mord mathnormal\\\" style=\\\"margin-right:0.02778em;\\\">O</span><span class=\\\"mopen\\\">(</span><span class=\\\"mop\\\">lo<span style=\\\"margin-right:0.01389em;\\\">g</span></span><span class=\\\"mspace\\\" style=\\\"margin-right:0.1667em;\\\"></span><span class=\\\"mord mathnormal\\\">n</span><span class=\\\"mclose\\\">)</span></span></span></span></p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
