export const themeData = JSON.parse("{\"encrypt\":{},\"author\":{\"name\":\"Goat_Yang\",\"url\":\"https://mister-hope.com\"},\"logo\":\"assets/icon/头像.jpg\",\"repo\":\"Yang-goat/MyBlog\",\"repoLabel\":\"GitHub\",\"repoDisplay\":true,\"docsDir\":\"src\",\"footer\":\"感谢访问\",\"displayFooter\":true,\"blog\":{\"description\":\"立志考研的程序员 爱好电音 信计本科在读\",\"intro\":\"/intro.html\",\"medias\":{\"BiliBili\":\"https://space.bilibili.com/415221098\",\"Email\":\"mailto:1700425119@qq.com\",\"GitHub\":\"https://github.com/Yang-goat\",\"QQ\":\"https://qm.qq.com/cgi-bin/qm/qr?k=W9kVREFn34sQS_QB1aGDmqoJ2-W4Lst_\",\"163Music\":\"https://music.163.com/#/user/home?id=1499103686\"}},\"print\":true,\"fullscreen\":false,\"pure\":false,\"pageInfo\":[\"Author\",\"Date\",\"Category\",\"Tag\",\"Word\",\"ReadingTime\"],\"locales\":{\"/\":{\"lang\":\"zh-CN\",\"navbarLocales\":{\"langName\":\"简体中文\",\"selectLangAriaLabel\":\"选择语言\"},\"metaLocales\":{\"author\":\"作者\",\"date\":\"写作日期\",\"origin\":\"原创\",\"views\":\"访问量\",\"category\":\"分类\",\"tag\":\"标签\",\"readingTime\":\"阅读时间\",\"words\":\"字数\",\"toc\":\"此页内容\",\"prev\":\"上一页\",\"next\":\"下一页\",\"contributors\":\"贡献者\",\"editLink\":\"在 GitHub 上编辑此页\",\"print\":\"打印\"},\"blogLocales\":{\"article\":\"文章\",\"articleList\":\"文章列表\",\"category\":\"分类\",\"tag\":\"标签\",\"timeline\":\"时间轴\",\"timelineTitle\":\"昨日不在\",\"all\":\"全部\",\"intro\":\"个人介绍\",\"star\":\"星标\",\"empty\":\"$text 为空\"},\"paginationLocales\":{\"prev\":\"上一页\",\"next\":\"下一页\",\"navigate\":\"跳转到\",\"action\":\"前往\",\"errorText\":\"请输入 1 到 $page 之前的页码！\"},\"outlookLocales\":{\"themeColor\":\"主题色\",\"darkmode\":\"外观\",\"fullscreen\":\"全屏\"},\"routerLocales\":{\"skipToContent\":\"跳至主要內容\",\"notFoundTitle\":\"页面不存在\",\"notFoundMsg\":[\"这里什么也没有\",\"我们是怎么来到这儿的？\",\"这 是 四 零 四 !\",\"看起来你访问了一个失效的链接\"],\"back\":\"返回上一页\",\"home\":\"带我回家\"},\"navbar\":[\"/\",{\"text\":\"笔记\",\"icon\":\"book\",\"link\":\"/笔记/\"},{\"text\":\"算法\",\"icon\":\"code\",\"link\":\"/算法/\"},{\"text\":\"随笔\",\"icon\":\"pen-to-square\",\"link\":\"/随笔/\"},{\"text\":\"实用工具教程\",\"icon\":\"toolbox\",\"link\":\"/实用工具教程/\"},{\"text\":\"宝藏站点\",\"icon\":\"link\",\"link\":\"/link\"},{\"text\":\"关于我\",\"icon\":\"user\",\"link\":\"/intro\"}],\"sidebar\":{\"/笔记/\":[\"\",{\"text\":\"程序设计语言\",\"icon\":\"code\",\"prefix\":\"程序设计语言/\",\"link\":\"程序设计语言/\",\"children\":[{\"text\":\"Java\",\"icon\":\"code\",\"prefix\":\"java/\",\"link\":\"java/\",\"collapsible\":true,\"expanded\":false,\"children\":\"structure\"},{\"text\":\"python\",\"icon\":\"code\",\"prefix\":\"python/\",\"link\":\"python/\",\"collapsible\":true,\"expanded\":false,\"children\":\"structure\"}]},{\"text\":\"前端\",\"icon\":\"laptop-code\",\"prefix\":\"前端/\",\"link\":\"前端/\",\"children\":\"structure\"}],\"/算法/\":\"structure\",\"/随笔/\":\"structure\",\"/实用工具教程/\":\"structure\"}}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
