import comp from "D:/Project/Blog/myBlog/src/.vuepress/.temp/pages/dev/frontend/ThreeBasics/html.html.vue"
const data = JSON.parse("{\"path\":\"/dev/frontend/ThreeBasics/html.html\",\"title\":\"HTML\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"pen-to-square\",\"date\":\"2025-10-20T00:00:00.000Z\",\"order\":1,\"category\":[\"前端\"],\"tag\":[\"html\"],\"description\":\"HTML 不分大小写、有单标签和双标签 基础格式 标签 head中 body中 基础 通用属性： 文字颜色属性 text 页面背景颜色 bgcolor 标题（鼠标放置显示）title 拖放属性 draggable=\\\"true\\\" style css行内样式，分号隔开多个样式 class 空格隔开多个 id 转义字符 超链接 列表 层标记 范围标签 表格 ...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"HTML\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2025-10-20T00:00:00.000Z\\\",\\\"dateModified\\\":\\\"2025-10-21T07:08:14.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Goat_Yang\\\",\\\"url\\\":\\\"../intro.html\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/Yang-goat/MyBlog/dev/frontend/ThreeBasics/html.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Goat_Yang\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"HTML\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"HTML 不分大小写、有单标签和双标签 基础格式 标签 head中 body中 基础 通用属性： 文字颜色属性 text 页面背景颜色 bgcolor 标题（鼠标放置显示）title 拖放属性 draggable=\\\"true\\\" style css行内样式，分号隔开多个样式 class 空格隔开多个 id 转义字符 超链接 列表 层标记 范围标签 表格 ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2025-10-21T07:08:14.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"html\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-10-20T00:00:00.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2025-10-21T07:08:14.000Z\"}]]},\"git\":{\"createdTime\":1761030494000,\"updatedTime\":1761030494000,\"contributors\":[{\"name\":\"Yang-goat\",\"username\":\"Yang-goat\",\"email\":\"1700425119@qq.com\",\"commits\":1,\"url\":\"https://github.com/Yang-goat\"}]},\"readingTime\":{\"minutes\":3.6,\"words\":1081},\"filePathRelative\":\"dev/frontend/ThreeBasics/html.md\",\"excerpt\":\"\\n<p>不分大小写、有单标签和双标签</p>\\n<div class=\\\"language-html line-numbers-mode\\\" data-highlighter=\\\"shiki\\\" data-ext=\\\"html\\\" style=\\\"--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34\\\"><pre class=\\\"shiki shiki-themes one-light one-dark-pro vp-code\\\"><code class=\\\"language-html\\\"><span class=\\\"line\\\"><span style=\\\"--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic\\\">&lt;!-- 注释信息 --&gt;</span></span></code></pre>\\n<div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\" style=\\\"counter-reset:line-number 0\\\"><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
