name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: 调试：显示环境信息
        run: |
          echo "Node 版本:"
          node --version
          echo "npm 版本:"
          npm --version
          echo "PATH:"
          echo $PATH
          echo "当前目录内容:"
          ls -la

      - name: 调试：检查 pnpm 路径
        run: |
          which pnpm
          ls -la $(dirname $(which pnpm))

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 构建项目
        run: pnpm docs:build

      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./scr/.vuepress/dist
          publish_branch: gh-pages  # 明确部署目标分支
          github_token: ${{ secrets.GITHUB_TOKEN }}
