import comp from "/media/goat/双系统共享/project/Blog/myBlog/src/.vuepress/.temp/pages/guides/linux/common.html.vue"
const data = JSON.parse("{\"path\":\"/guides/linux/common.html\",\"title\":\"Ubuntu 常用指令速查笔记\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"book\",\"date\":\"2025-11-10T00:00:00.000Z\",\"category\":[\"Linux\",\"Ubuntu\"],\"tag\":[\"命令行\",\"Shell\"],\"description\":\"Ubuntu 常用指令速查笔记 整理常见、实用的 Ubuntu 命令，按场景分类速查。 📁 文件与目录操作 ⚙️ 系统管理与信息查看 👤 用户与权限管理 🧩 软件包管理（APT） 🌐 网络命令 🧠 进程与服务管理 🔒 SSH 与远程管理 🧾 日志与调试 🧰 实用工具命令 ✅ 小贴士 使用 Tab 键可自动补全命令或文件名 使用 Ctrl...\"},\"git\":{},\"readingTime\":{\"minutes\":4.32,\"words\":1296},\"filePathRelative\":\"guides/linux/common.md\",\"excerpt\":\"\\n<p>整理常见、实用的 Ubuntu 命令，按场景分类速查。</p>\\n<hr>\\n<h2>📁 文件与目录操作</h2>\\n<table>\\n<thead>\\n<tr>\\n<th>功能</th>\\n<th>命令示例</th>\\n<th>说明</th>\\n</tr>\\n</thead>\\n<tbody>\\n<tr>\\n<td>查看当前路径</td>\\n<td><code>pwd</code></td>\\n<td>打印当前工作目录</td>\\n</tr>\\n<tr>\\n<td>列出文件</td>\\n<td><code>ls -l</code> / <code>ls -al</code></td>\\n<td>显示详细列表 / 包含隐藏文件</td>\\n</tr>\\n<tr>\\n<td>进入目录</td>\\n<td><code>cd /path/to/dir</code></td>\\n<td>切换工作目录</td>\\n</tr>\\n<tr>\\n<td>返回上级目录</td>\\n<td><code>cd ..</code></td>\\n<td>返回上一级目录</td>\\n</tr>\\n<tr>\\n<td>创建目录</td>\\n<td><code>mkdir \\\"mydir\\\"</code></td>\\n<td>新建目录</td>\\n</tr>\\n<tr>\\n<td>创建多级目录</td>\\n<td><code>mkdir -p \\\"a/b/c\\\"</code></td>\\n<td>一次创建多层</td>\\n</tr>\\n<tr>\\n<td>删除文件</td>\\n<td><code>rm \\\"file.txt\\\"</code></td>\\n<td>删除单个文件</td>\\n</tr>\\n<tr>\\n<td>删除目录</td>\\n<td><code>rm -rf \\\"dirname\\\"</code></td>\\n<td>强制删除目录及内容</td>\\n</tr>\\n<tr>\\n<td>复制文件</td>\\n<td><code>cp file1 file2</code></td>\\n<td>复制文件</td>\\n</tr>\\n<tr>\\n<td>复制目录</td>\\n<td><code>cp -r dir1 dir2</code></td>\\n<td>递归复制目录</td>\\n</tr>\\n<tr>\\n<td>移动或重命名</td>\\n<td><code>mv old new</code></td>\\n<td>移动或重命名文件或目录</td>\\n</tr>\\n<tr>\\n<td>查看文件内容</td>\\n<td><code>cat file</code> / <code>less file</code> / <code>head -n 10 file</code></td>\\n<td>快速查看文件内容</td>\\n</tr>\\n<tr>\\n<td>搜索文件</td>\\n<td><code>find / -name \\\"*.conf\\\"</code></td>\\n<td>查找配置文件</td>\\n</tr>\\n<tr>\\n<td>查找文本</td>\\n<td><code>grep \\\"pattern\\\" filename</code></td>\\n<td>按内容搜索文件</td>\\n</tr>\\n<tr>\\n<td>压缩文件</td>\\n<td><code>tar -czvf archive.tar.gz folder</code></td>\\n<td>创建压缩包</td>\\n</tr>\\n<tr>\\n<td>解压文件</td>\\n<td><code>tar -xzvf archive.tar.gz</code></td>\\n<td>解压压缩包</td>\\n</tr>\\n</tbody>\\n</table>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
