import comp from "/media/goat/data/project/Blog/myBlog/src/.vuepress/.temp/pages/guides/linux/command.html.vue"
const data = JSON.parse("{\"path\":\"/guides/linux/command.html\",\"title\":\"Ubuntu 常用指令\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"book\",\"date\":\"2025-11-11T00:00:00.000Z\",\"order\":2,\"category\":[\"Linux\",\"Ubuntu\"],\"tag\":[\"命令行\",\"Shell\"],\"description\":\"Ubuntu 常用指令 整理常见、实用的 Ubuntu 命令，按场景分类速查。 清空控制台 或直接按快捷键：Ctrl + L 📁 文件与目录操作 ⚙️ 系统管理与信息查看 👤 用户与权限管理 🧩 软件包管理（APT） 🌐 网络命令 🧠 进程与服务管理 🔒 SSH 与远程管理 🧾 日志与调试 🧰 实用工具命令 🎮 NVIDIA GPU ...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Ubuntu 常用指令\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2025-11-11T00:00:00.000Z\\\",\\\"dateModified\\\":\\\"2025-12-14T13:57:45.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Goat_Yang\\\",\\\"url\\\":\\\"../intro.html\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://github.com/Yang-goat/MyBlog/guides/linux/command.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"Goat_Yang\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Ubuntu 常用指令\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Ubuntu 常用指令 整理常见、实用的 Ubuntu 命令，按场景分类速查。 清空控制台 或直接按快捷键：Ctrl + L 📁 文件与目录操作 ⚙️ 系统管理与信息查看 👤 用户与权限管理 🧩 软件包管理（APT） 🌐 网络命令 🧠 进程与服务管理 🔒 SSH 与远程管理 🧾 日志与调试 🧰 实用工具命令 🎮 NVIDIA GPU ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2025-12-14T13:57:45.000Z\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Shell\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"命令行\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-11-11T00:00:00.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2025-12-14T13:57:45.000Z\"}]]},\"git\":{\"createdTime\":1762832288000,\"updatedTime\":1765720665000,\"contributors\":[{\"name\":\"Yang-goat\",\"username\":\"Yang-goat\",\"email\":\"1700425119@qq.com\",\"commits\":2,\"url\":\"https://github.com/Yang-goat\"}]},\"readingTime\":{\"minutes\":6.29,\"words\":1887},\"filePathRelative\":\"guides/linux/command.md\",\"excerpt\":\"\\n<p>整理常见、实用的 Ubuntu 命令，按场景分类速查。</p>\\n<p>清空控制台</p>\\n<div class=\\\"language-bash line-numbers-mode\\\" data-highlighter=\\\"shiki\\\" data-ext=\\\"bash\\\" style=\\\"--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34\\\"><pre class=\\\"shiki shiki-themes one-light one-dark-pro vp-code\\\"><code class=\\\"language-bash\\\"><span class=\\\"line\\\"><span style=\\\"--shiki-light:#4078F2;--shiki-dark:#61AFEF\\\">clear</span></span></code></pre>\\n<div class=\\\"line-numbers\\\" aria-hidden=\\\"true\\\" style=\\\"counter-reset:line-number 0\\\"><div class=\\\"line-number\\\"></div></div></div>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
